### ISSUE TITLE
Config file of unsupervised method

### ISSUE THREAD

**Issue by milliema** [PhysiologicAILab/FactorizePhys#2]
Hi, thans for your great work! I am new to rPPG analysis, and I found your work very helpful.
I am trying to start with the unsupervised analysis, where can I find the config file such as "PURE_UNSUPERVISED.yaml" and "UBFC-rPPG_UNSUPERVISED.yaml" mentioned in https://github.com/PhysiologicAILab/FactorizePhys/blob/8cd115145eb0a3c17941a4286a224a49d2ab687c/main.py#L57-L59?

**Comment by milliema** [comment]
In addition, after face detection and cropping, is there any ROI selection based on the facial landmarks? Is tracking strategy used to track the movement and compute the color change for each correspond region? 
Thanks!

**Comment by jnj256** [comment]
Regarding config files for unsupervised methods, these were not kept in the repository as in our paper we do not compare against unsupervised methods. Though you can find them in rPPG-Toolbox repo here -> https://github.com/ubicomplab/rPPG-Toolbox/tree/main/configs/infer_configs

**Comment by jnj256** [comment]
Based on face detection, the bounding box is used to crop an image. Landmarks points are not used for tracking. Entire cropped image is used as an input for supervised neural methods.

**Comment by jnj256** [comment]
Please feel free to re-open this issue if you have more queries.
